### PR TITLE
Feature/dynamic group info page frontend

### PR DESCRIPTION
**Pull request by xinranwangxwan559**
group info page implemented all buttons, connect with backend database.

### CODE REVIEW

**Comment by ryanwooa** [comment]
image
- In red area, these two div don't have a gray cover
- orange: the input better have same width as buttons
- blue: gap should be larger

 {
        "_id": "66289824101d072e9a9650a7",
        "groupName": "chelsea test group",
        "createDate": "2024-04-24T05:27:00.098Z",
        "deadlineDate": "2024-04-30T00:00:00.000Z",
        "numberOfGroupMember": 5,
        "groupMembers": [
            "6627822e44685f17db7d86ce"
        ],
        "groupApplicants": [
            "66263514fbb9cd9cafb7fee4"
        ],
        "groupDescription": "need cat, dog, apple, banana, orange",
        "groupTags": [
            "66289823101d072e9a9650a1",
            "66289823101d072e9a96509f",
            "66289823101d072e9a96509d",
            "66289824101d072e9a9650a5",
            "66289824101d072e9a9650a3"
        ],
        "ownerId": "6627822e44685f17db7d86ce",
        "groupStatus": "available",
        "groupType": "group",
        "__v": 3,
        "application": [
            "6629cea3a9bd430a0ca3a25e"
        ]
    },
image

For this group, doesn't show the owner on the page

**Comment by ryanwooa** [comment]
- After someone applied for the group, or owner accept the applicant, the Applicants list/Member list should refresh to add this new applicant
- "Application Message" how about change a title?
- How about add a link for owner to view the infomation of the applicants
- How about reduce the use of alert for notifiy, like "accept successfully" or "Reject successfully". Need to click too many times.

**Comment by tpan501** [comment]
image
The message display has a little bug if the applicant type a very long word. just let you know but normally nobody does that.

**Comment by xinranwangxwan559** [comment]
> image
> 
> * In red area, these two div don't have a gray cover
> * orange: the input better have same width as buttons
> * blue: gap should be larger
> 
> { "_id": "66289824101d072e9a9650a7", "groupName": "chelsea test group", "createDate": "2024-04-24T05:27:00.098Z", "deadlineDate": "2024-04-30T00:00:00.000Z", "numberOfGroupMember": 5, "groupMembers": [ "6627822e44685f17db7d86ce" ], "groupApplicants": [ "66263514fbb9cd9cafb7fee4" ], "groupDescription": "need cat, dog, apple, banana, orange", "groupTags": [ "66289823101d072e9a9650a1", "66289823101d072e9a96509f", "66289823101d072e9a96509d", "66289824101d072e9a9650a5", "66289824101d072e9a9650a3" ], "ownerId": "6627822e44685f17db7d86ce", "groupStatus": "available", "groupType": "group", "__v": 3, "application": [ "6629cea3a9bd430a0ca3a25e" ] }, image
> 
> For this group, doesn't show the owner on the page

this group ownerId is missing or null, i have tested all ohers group which works

**Review by ChelseaHuang748 — APPROVED** [review]

**Review by zli213 — APPROVED** [review]

**Review by ryanwooa — APPROVED** [review]

**Review by jlmjkfd — APPROVED** [review]

**Review by tpan501 — APPROVED** [review]

**Pull request merged**
